name: 自動更新提交日期

# 觸發條件：當有推送（push）事件到 main 分支時觸發此工作流
on:
  push:
    branches:
      - main

# 定義任務
jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    # 使用 GitHub API 更新文件内容
    - name: 更新 config/updatetime.txt 文檔
      uses: actions/github-script@v6
      with:
        script: |
          //完全不會學這個, 交給通義寫叭。
        
          // 引用外部庫
          let fs = require('fs');
          // let github = require('@actions/github');
          // let context = require('@actions/github');
          let { context, github } = require('@actions/github');
          
          let now = new Date();
          let nowtime = time.getFullYear() + "-" + (time.getMonth() + 1) + "-" + time.getDate() + " " + String(time.getHours()).padStart(2, '0') + ":" + String(time.getMinutes()).padStart(2, '0') + ":" + String(time.getSeconds()).padStart(2, '0');

          try {
            // 寫入文檔
            fs.writeFileSync("${process.env.GITHUB_WORKSPACE}/config", nowtime);
            let content = Buffer.from(nowtime).toString('base64');

              await github.rest.repos.createOrUpdateFileContents({
                ...context.repo,
                path: "config/updatetime.txt",
                message: "更新日期",
                content: content,
                branch: context.ref.replace('refs/heads/', '')
              });
          }
          catch(err){
            console.log("错误: \r\n" + err);
          }