name: 自動更新提交日期

# 觸發條件：當有推送（push）事件到 main 分支時觸發此工作流
on:
  push:
    branches:
      - main

# 定義任務
jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    # 使用 GitHub API 更新文件内容
    - name: 創建文件夾
      run: mkdir -p ./config/
    
    - name: 更新 config/updatetime.txt 文檔
      uses: actions/github-script@v6
      with:
        script: |
          //完全不會學這個, 交給通義寫叭。
        
          // 引用外部庫
          let fs = require('fs');
          // let github = require('@actions/github');
          // let context = require('@actions/github');
          // let { context, github } = require('@actions/github');

          //獲取當前時間
          function gettime(){
            let now = new Date();
            let nowtime = now.getFullYear() + "-" + (now.getMonth() + 1) + "-" + now.getDate() + " " + String(now.getHours()).padStart(2, '0') + ":" + String(now.getMinutes()).padStart(2, '0') + ":" + String(now.getSeconds()).padStart(2, '0');
            return nowtime;
          }
          
          console.log("# " + gettime() + " | 準備嘗試。。。");
          
          try {
            // 寫入文檔
            //fs.writeFileSync("${process.env.GITHUB_WORKSPACE}/config", nowtime);
            let content = Buffer.from(gettime()).toString('base64');

              await github.rest.repos.createOrUpdateFileContents({
                ...context.repo,
                path: "config/updatetime.txt",
                message: "更新日期",
                content: content,
                branch: context.ref.replace('refs/heads/', '')
              });
          }
          catch(err){
            console.log("# " + gettime() + " | 遇到错误了欸: \r\n" + err.stack);
          }
          console.log("# " + gettime() + " | 完成咯! ");

          
